### ISSUE TITLE
Bug, use skill 2 while farming raid with Relic Buster class

### ISSUE THREAD

**Issue by stijnvcp** [steve1316/granblue-automation-pyautogui#21]
Bug I encountered while trying to farm performing a skill 1 and skill 2 using relic buster to ougi.
![image](https://user-images.githubusercontent.com/75256118/113361246-5fb65500-9300-11eb-8a0f-7f0790b86318.png)

cursor stuck hovering skill 1.
![image](https://user-images.githubusercontent.com/75256118/113361285-7a88c980-9300-11eb-8719-261f879aa10f.png)

**Comment by steve1316** [comment]
Whoops! Turns out I was not as thorough as I thought when I updated the references to the new random shift feature. Now the references should be working now. Let me know how it goes!

**Comment by stijnvcp** [comment]
It works but it's still having an exception pop up when it tries to click the skill 
![image](https://user-images.githubusercontent.com/75256118/113566686-05e4b200-95c2-11eb-9705-1d23197b1343.png)

**Comment by steve1316** [comment]
Just updated the bot to fix the issue as I forgot to upload the image asset for the "Back" button. Let me know how it goes!
